name: 0.1.$(Rev:r)

variables:
  tag: v$(Build.BuildNumber)

trigger:
  - master
  - feature/*

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              git config user.email 'pipelines@gwyddiongames.com'
              git config user.name 'Pipeline Automation User'
            displayName: Set up Git

          - task: Go@0
            displayName: go version
            inputs:
              command: 'custom'
              customCommand: 'version'

# TODO: Re-enable testing once getting opengl dependencies with compiling is understood on build agent
#          - task: Go@0
#            displayName: go test
#            inputs:
#              command: 'test'
#              arguments: './...'

          - script: |
              git tag $(tag)
              git push origin $(tag)
            displayName: Tag Repo
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

          - script: |
              git tag $(tag).dev
              git push origin $(tag).dev
            displayName: Tag Repo with Dev
            condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
